services:
  - type: web
    name: team-mineflayer-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: MC_HOST
        value: "serverplayer1235.aternos.me"
      - key: MC_PORT
        value: "12490"
      - key: MC_USERNAME
        value: "AutoBot"
      - key: MC_VERSION
        value: ""
      - key: MC_AUTH
        value: "offline"
      - key: BOT_COUNT
        value: "3"
